version: "3.9"

services:
  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./frontend:/app
    depends_on:
      - backend

  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend
    ports:
      - "5000:5000"
    volumes:
      - /app/node_modules
      - ./backend:/app
